### ISSUE TITLE
States not working with pre-existing boards/tokens

### ISSUE THREAD

**Issue by demongund** [LordAshes/TaleSpire-StatesPlugin#3] opened 2021-06-04 04:23 UTC
If I start TaleSpire with the plugin active, then try to add a state to a pre-existing token, the states do not display. This is also true if you try to do manual colored states.

If I then create a new board and add new tokens, the states work beautifully.

**Comment by LordAshes** [comment] 2021-06-04 14:30
I am unable to reproduce this problem. I loaded a pre-existing board with pre-existing tokens and I was able to add States to them without any issue. The colorization also triggered properly.

However, I did not that the stats were loading at a 90 degree angle to the mini. Is it possible that they loaded but you did not see them because you were looking straight on to the mini?

If not, can you do a short screen capture video because, as I said, I don't seem to have the problem.

**Comment by LordAshes** [comment] 2021-06-16 02:19
This issue was related to two bugs. One was a timing issue preventing existing states from being restored and the other bug was one that was preventing states from being modified once added. Both bugs have been fixed in version 2.0.1

**Closed by LordAshes** 2021-06-16 02:19 UTC
